**python 3 - true division**

In [3]:
#complex number
a = 2 + 3j
type(a)

complex

In [6]:
b = 3 + 4j

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a.conjugate())
print(abs(a))

(5+7j)
(-1-1j)
(-6+17j)
(0.72+0.04j)
(2-3j)
3.605551275463989


**Sequence Types**
<pre>
string
list
tuple
range
</pre>

**Mapping Type**
<pre>
Dictionary
</pre>pre>

**set**
<pre> 
set
frozenset
</pre>

**boolean**
<pre> 
True
False
</pre>
**binary type**
<pre> 
byte
bytearray
memoryview
</pre>
**nonetype**
<pre> 
None
</pre>

In [9]:
#dictionary
dict = {1: 'kuhan', 2: 'login360'}
print(dict[1])

dict2 = {"apple": 250, "banana": 200}
print(dict2["apple"])

dict3 = {(1,2):"canada", (2,3):"america"}
print(dict3[(1,2)])

kuhan
250
canada


**dictionary key can be any immutable datatype**
<pre>
numbers, strings, tuples, and even frozenset
key: unique and hashable  

Mutable data types like lists, dictionaries, or sets cannot be used as keys
    
</pre>

In [54]:
#dict_error = {[1,2,3]:"kuhan"}
#print(dict_error[1,2,3])

In [108]:
dic = {"name": "kuhan", "Age":30, "qualification": "Engineering"}
dic["qualification"]= "MBA"
dic["address"] = "Chennai"
del dic["Age"]
print(dic)
print(dic.items(), dic.values(), dic.keys())
for k, v in dic.items():
    print("key:",k, "&\tValue:", v)
dic2 = {"parents":True}
dic.update(dic2)
dic

{'name': 'kuhan', 'qualification': 'MBA', 'address': 'Chennai'}
dict_items([('name', 'kuhan'), ('qualification', 'MBA'), ('address', 'Chennai')]) dict_values(['kuhan', 'MBA', 'Chennai']) dict_keys(['name', 'qualification', 'address'])
key: name &	Value: kuhan
key: qualification &	Value: MBA
key: address &	Value: Chennai


{'name': 'kuhan',
 'qualification': 'MBA',
 'address': 'Chennai',
 'parents': True}

**sets**

In [55]:
#sets
set1 = {1,2,3,3,1}
set1

{1, 2, 3}

In [56]:
#uniqueness
data = [1, 2, 2, 3, 4, 4, 5]
unique_data = set(data)
print(unique_data)

#membership testing
print(1 in unique_data)

#mathematical operation
set2 = {4,5,6,7}
print(unique_data | set2) # union
print(unique_data & set2) # intersection
print(unique_data.intersection(set2))
print(unique_data - set2) # difference
print(set2 - unique_data) # difference
print(set2 ^ unique_data) # symmetric difference

word = "python is a great language python python language"
print(set(word.split())) # remove duplicate words

#handling unique ids
ids ={1,2,3,4}
i=5
if i not in ids:
    ids.add(i)
print(ids)

{1, 2, 3, 4, 5}
True
{1, 2, 3, 4, 5, 6, 7}
{4, 5}
{4, 5}
{1, 2, 3}
{6, 7}
{1, 2, 3, 6, 7}
{'language', 'python', 'is', 'great', 'a'}
{1, 2, 3, 4, 5}


In [57]:
set1={1,2,3}
set1.add(4)
# set1.update(5) # error because not iteratable
set1.update((10,2), [1,5,7,8], {88,3}) # add iteratable element
set1

{1, 2, 3, 4, 5, 7, 8, 10, 88}

In [115]:
# forzenset
fs = frozenset([1,2,3])
print(fs)
#fs.add(4)
fss=set(fs)
fss.add(4)
fss

frozenset({1, 2, 3})


{1, 2, 3, 4}

**None Type**

In [58]:
value = None
print(type(value))
print(id(value))

<class 'NoneType'>
140716084986352


**list - mutable, ordered, different datatype - allowes indexing, slicing and other operations**

In [59]:
list1 = [1,2,3]
list2=[1,"kuhan",[1,2]]
list2

[1, 'kuhan', [1, 2]]

In [60]:
print(list2[-1])
print(list2[0])
print(list2[:3])
print(list2[::-1])
print(list2[2][1])
print(list2[1:2]) # not include ending index element

[1, 2]
1
[1, 'kuhan', [1, 2]]
[[1, 2], 'kuhan', 1]
2
['kuhan']


In [61]:
list2.append(3)
list2.insert(0,99)
list2.extend([1,2])
list2

[99, 1, 'kuhan', [1, 2], 3, 1, 2]

In [62]:
list2.remove(99)
list2.pop(3)
list2

[1, 'kuhan', [1, 2], 1, 2]

In [63]:
list2.clear()

In [64]:
list2

[]

In [66]:
lst = [1,2,3,4,2,3,2]
for i in lst:
    print(i)



1
2
3
4
2
3
2


In [67]:
print(lst.count(2))
print(lst.index(3))

3
2


In [68]:
lst.sort()
lst

[1, 2, 2, 2, 3, 3, 4]

In [76]:
list(reversed(lst))

[4, 3, 3, 2, 2, 2, 1]

In [77]:
list(sorted(lst))

[1, 2, 2, 2, 3, 3, 4]

**list comphrehension**

concise and elegant way to create lists in Python. It allows you to construct a new list by applying an expression to each element of an iterable (like a list, range, or tuple) and optionally filtering elements with a condition.

In [81]:
lst2 = [x for x in range(5)]
print(lst2)
lst2 = [x**2 for x in range(5)]
print(lst2)

[0, 1, 2, 3, 4]
[0, 1, 4, 9, 16]


In [89]:
lst = [x for x in range(10) if x % 2==0]
lst
lst2 = [(x,y) for x in range(2) for y in range(3)]
print(lst2)
lst3 = [x for x in lst2]
print(lst3)

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2)]
[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2)]


In [90]:
mat = [[1,2,3], [2,4,5]]
lst = [x for y in mat for x in y]
lst #flattened nested list

[1, 2, 3, 2, 4, 5]

In [97]:
#multiplication table
eleventable = [x*11 for x in range(3,11)]
eleventable

#identify vowels
name = "kuhan kailasanathan"
vowels = [i for i in name if i in 'aeiou']
set(vowels)

{'a', 'i', 'u'}

In [119]:
#binary
a = 0b1010
print(a)

10


In [131]:
# some import topic
#get memory details
a=43
b= "kuhan"
c=[1,2,3]
d=43
import sys
print(sys.getsizeof(a), id(a))
print(sys.getsizeof(b), id(b))
print(sys.getsizeof(c), id(c))
print(sys.getsizeof(c), id(d))
c.append(4)
print(sys.getsizeof(c), id(c))

28 140716085872872
46 2719344381696
88 2719352660672
88 140716085872872
88 2719352660672


In [134]:
#shallow copy and Deep copy
import copy

lst = [1,2,[3,4]]
lst2 = copy.copy(lst)
print(lst2[2][0])
lst2[2][0]=99
print(lst)
print(lst2)

3
[1, 2, [99, 4]]
[1, 2, [99, 4]]


In [135]:
lst = [1,2,[3,4]]
lst2 = copy.deepcopy(lst)
print(lst2[2][0])
lst2[2][0]=99
print(lst)
print(lst2)

3
[1, 2, [3, 4]]
[1, 2, [99, 4]]


In [140]:
lst3= lst[:]
lst3[2][0]=99
print(lst)
print(lst3)

dic = {1:"A", 2:[1,2]}
dic2= dic.copy()
dic2[2][1]=5
print(dic)
print(dic2)

[1, 2, [99, 4]]
[1, 2, [99, 4]]
{1: 'A', 2: [1, 5]}
{1: 'A', 2: [1, 5]}


In [146]:
#deep copy using list comprehension
#list comprehension: [expression for item in itereable if condition]
lst = [1,2,[3,4]]
lst2 = [x[:] if isinstance(x, list) else x for x in lst]
print(lst2)
lst2[2][1]=99
print(lst)
print(lst2)

[1, 2, [3, 4]]
[1, 2, [3, 4]]
[1, 2, [3, 99]]


In [150]:
import numpy as np
mat = np.array([[1,2,3],[2,3,4],[5,6,7]])
mat2 = np.array([[1,2,3],[2,3,4],[5,6,7]])
print(np.dot(mat,mat2))

[[ 1  4  9]
 [ 4  9 16]
 [25 36 49]]
[[20 26 32]
 [28 37 46]
 [52 70 88]]


In [151]:
lst = [1,2,3]
arr = np.array([1,2,3])
lst = [x*2 for x in lst]
arr = arr*2
print(lst)
print(arr)

[2, 4, 6]
[2 4 6]


In [152]:
lst = [1,2]
lst2 = [3,4]
lst3 = [x + y for x,y in zip(lst, lst2)]
lst3

[4, 6]

In [153]:
arr = np.array([1,2])
arr2 = np.array([3,4])
arr+arr2

array([4, 6])